//------------------------------------------------------------------------------
// <auto-generated>
//     The generated half, named so it sorts FIRST and is therefore the declaration
//     SolutionClassifier reports as the type's primary file. Filtering generated-ness on that
//     one file skipped the whole type, handwritten half included.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleSolution.Services;

public partial class GeneratedPrimaryFixture
{
    private int GeneratedPrimaryStep(int i) => i + 2;

    private int GeneratedPrimaryWork()
    {
        int total = 0;
        total += GeneratedPrimaryStep(0);
        total += GeneratedPrimaryStep(1);
        total += GeneratedPrimaryStep(2);
        total += GeneratedPrimaryStep(3);
        total += GeneratedPrimaryStep(4);
        total += GeneratedPrimaryStep(5);
        total += GeneratedPrimaryStep(6);
        total += GeneratedPrimaryStep(7);
        total += GeneratedPrimaryStep(8);
        total += GeneratedPrimaryStep(9);
        total += GeneratedPrimaryStep(10);
        total += GeneratedPrimaryStep(11);
        total += GeneratedPrimaryStep(12);
        total += GeneratedPrimaryStep(13);
        total += GeneratedPrimaryStep(14);
        total += GeneratedPrimaryStep(15);
        total += GeneratedPrimaryStep(16);
        total += GeneratedPrimaryStep(17);
        total += GeneratedPrimaryStep(18);
        total += GeneratedPrimaryStep(19);
        total += GeneratedPrimaryStep(20);
        total += GeneratedPrimaryStep(21);
        total += GeneratedPrimaryStep(22);
        total += GeneratedPrimaryStep(23);
        total += GeneratedPrimaryStep(24);
        total += GeneratedPrimaryStep(25);
        total += GeneratedPrimaryStep(26);
        total += GeneratedPrimaryStep(27);
        total += GeneratedPrimaryStep(28);
        total += GeneratedPrimaryStep(29);
        total += GeneratedPrimaryStep(30);
        total += GeneratedPrimaryStep(31);
        total += GeneratedPrimaryStep(32);
        total += GeneratedPrimaryStep(33);
        total += GeneratedPrimaryStep(34);
        total += GeneratedPrimaryStep(35);
        total += GeneratedPrimaryStep(36);
        total += GeneratedPrimaryStep(37);
        total += GeneratedPrimaryStep(38);
        total += GeneratedPrimaryStep(39);
        total += GeneratedPrimaryStep(40);
        total += GeneratedPrimaryStep(41);
        total += GeneratedPrimaryStep(42);
        total += GeneratedPrimaryStep(43);
        total += GeneratedPrimaryStep(44);
        total += GeneratedPrimaryStep(45);
        total += GeneratedPrimaryStep(46);
        total += GeneratedPrimaryStep(47);
        total += GeneratedPrimaryStep(48);
        total += GeneratedPrimaryStep(49);
        total += GeneratedPrimaryStep(50);
        total += GeneratedPrimaryStep(51);
        return total;
    }
}
