//------------------------------------------------------------------------------
// <auto-generated>
//     The generated half, named so it sorts FIRST and is therefore the declaration
//     SolutionClassifier reports as the type's primary file. Filtering generated-ness on that
//     one file skipped the whole type, handwritten half included.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleSolution.Services;

public partial class GeneratedPrimaryFixture
{
    private int GeneratedPrimaryStep(int i) => i + 2;

    // Defining declaration only. GetMembers() returns this symbol; the body is in the other half.
    private partial int PartialWorkDefinedHere();

    private int GeneratedPrimaryWork()
    {
        int total = 0;
        if (total % 2 == 0) total += GeneratedPrimaryStep(0);
        if (total % 3 == 0) total += GeneratedPrimaryStep(1);
        if (total % 4 == 0) total += GeneratedPrimaryStep(2);
        if (total % 5 == 0) total += GeneratedPrimaryStep(3);
        if (total % 6 == 0) total += GeneratedPrimaryStep(4);
        if (total % 7 == 0) total += GeneratedPrimaryStep(5);
        if (total % 8 == 0) total += GeneratedPrimaryStep(6);
        if (total % 9 == 0) total += GeneratedPrimaryStep(7);
        if (total % 10 == 0) total += GeneratedPrimaryStep(8);
        if (total % 11 == 0) total += GeneratedPrimaryStep(9);
        if (total % 12 == 0) total += GeneratedPrimaryStep(10);
        if (total % 13 == 0) total += GeneratedPrimaryStep(11);
        if (total % 14 == 0) total += GeneratedPrimaryStep(12);
        if (total % 15 == 0) total += GeneratedPrimaryStep(13);
        if (total % 16 == 0) total += GeneratedPrimaryStep(14);
        if (total % 17 == 0) total += GeneratedPrimaryStep(15);
        if (total % 18 == 0) total += GeneratedPrimaryStep(16);
        if (total % 19 == 0) total += GeneratedPrimaryStep(17);
        if (total % 20 == 0) total += GeneratedPrimaryStep(18);
        if (total % 21 == 0) total += GeneratedPrimaryStep(19);
        if (total % 22 == 0) total += GeneratedPrimaryStep(20);
        if (total % 23 == 0) total += GeneratedPrimaryStep(21);
        if (total % 24 == 0) total += GeneratedPrimaryStep(22);
        if (total % 25 == 0) total += GeneratedPrimaryStep(23);
        if (total % 26 == 0) total += GeneratedPrimaryStep(24);
        if (total % 27 == 0) total += GeneratedPrimaryStep(25);
        if (total % 28 == 0) total += GeneratedPrimaryStep(26);
        if (total % 29 == 0) total += GeneratedPrimaryStep(27);
        if (total % 30 == 0) total += GeneratedPrimaryStep(28);
        if (total % 31 == 0) total += GeneratedPrimaryStep(29);
        if (total % 32 == 0) total += GeneratedPrimaryStep(30);
        if (total % 33 == 0) total += GeneratedPrimaryStep(31);
        if (total % 34 == 0) total += GeneratedPrimaryStep(32);
        if (total % 35 == 0) total += GeneratedPrimaryStep(33);
        if (total % 36 == 0) total += GeneratedPrimaryStep(34);
        if (total % 37 == 0) total += GeneratedPrimaryStep(35);
        if (total % 38 == 0) total += GeneratedPrimaryStep(36);
        if (total % 39 == 0) total += GeneratedPrimaryStep(37);
        if (total % 40 == 0) total += GeneratedPrimaryStep(38);
        if (total % 41 == 0) total += GeneratedPrimaryStep(39);
        if (total % 42 == 0) total += GeneratedPrimaryStep(40);
        if (total % 43 == 0) total += GeneratedPrimaryStep(41);
        if (total % 44 == 0) total += GeneratedPrimaryStep(42);
        if (total % 45 == 0) total += GeneratedPrimaryStep(43);
        if (total % 46 == 0) total += GeneratedPrimaryStep(44);
        if (total % 47 == 0) total += GeneratedPrimaryStep(45);
        if (total % 48 == 0) total += GeneratedPrimaryStep(46);
        if (total % 49 == 0) total += GeneratedPrimaryStep(47);
        if (total % 50 == 0) total += GeneratedPrimaryStep(48);
        if (total % 51 == 0) total += GeneratedPrimaryStep(49);
        if (total % 52 == 0) total += GeneratedPrimaryStep(50);
        if (total % 53 == 0) total += GeneratedPrimaryStep(51);
        return total;
    }
}
