//------------------------------------------------------------------------------
// <auto-generated>
//     This file is the generated half of a partial type. Nothing here is developer-written,
//     so the internal-complexity axis must not charge it — see GeneratedPartialFixture.cs.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleSolution.Services;

public partial class GeneratedPartialFixture
{
    private int GeneratedStep(int i) => i + 2;

    private int GeneratedWork()
    {
        int total = 0;
        total += GeneratedStep(0);
        total += GeneratedStep(1);
        total += GeneratedStep(2);
        total += GeneratedStep(3);
        total += GeneratedStep(4);
        total += GeneratedStep(5);
        total += GeneratedStep(6);
        total += GeneratedStep(7);
        total += GeneratedStep(8);
        total += GeneratedStep(9);
        total += GeneratedStep(10);
        total += GeneratedStep(11);
        total += GeneratedStep(12);
        total += GeneratedStep(13);
        total += GeneratedStep(14);
        total += GeneratedStep(15);
        total += GeneratedStep(16);
        total += GeneratedStep(17);
        total += GeneratedStep(18);
        total += GeneratedStep(19);
        total += GeneratedStep(20);
        total += GeneratedStep(21);
        total += GeneratedStep(22);
        total += GeneratedStep(23);
        total += GeneratedStep(24);
        total += GeneratedStep(25);
        total += GeneratedStep(26);
        total += GeneratedStep(27);
        total += GeneratedStep(28);
        total += GeneratedStep(29);
        total += GeneratedStep(30);
        total += GeneratedStep(31);
        total += GeneratedStep(32);
        total += GeneratedStep(33);
        total += GeneratedStep(34);
        total += GeneratedStep(35);
        total += GeneratedStep(36);
        total += GeneratedStep(37);
        total += GeneratedStep(38);
        total += GeneratedStep(39);
        total += GeneratedStep(40);
        total += GeneratedStep(41);
        total += GeneratedStep(42);
        total += GeneratedStep(43);
        total += GeneratedStep(44);
        total += GeneratedStep(45);
        total += GeneratedStep(46);
        total += GeneratedStep(47);
        total += GeneratedStep(48);
        total += GeneratedStep(49);
        total += GeneratedStep(50);
        total += GeneratedStep(51);
        return total;
    }
}
