//------------------------------------------------------------------------------
// <auto-generated>
//     This file is the generated half of a partial type. Nothing here is developer-written,
//     so the internal-complexity axis must not charge it — see GeneratedPartialFixture.cs.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleSolution.Services;

public partial class GeneratedPartialFixture
{
    private int GeneratedStep(int i) => i + 2;

    private int GeneratedWork()
    {
        int total = 0;
        if (total % 2 == 0) total += GeneratedStep(0);
        if (total % 3 == 0) total += GeneratedStep(1);
        if (total % 4 == 0) total += GeneratedStep(2);
        if (total % 5 == 0) total += GeneratedStep(3);
        if (total % 6 == 0) total += GeneratedStep(4);
        if (total % 7 == 0) total += GeneratedStep(5);
        if (total % 8 == 0) total += GeneratedStep(6);
        if (total % 9 == 0) total += GeneratedStep(7);
        if (total % 10 == 0) total += GeneratedStep(8);
        if (total % 11 == 0) total += GeneratedStep(9);
        if (total % 12 == 0) total += GeneratedStep(10);
        if (total % 13 == 0) total += GeneratedStep(11);
        if (total % 14 == 0) total += GeneratedStep(12);
        if (total % 15 == 0) total += GeneratedStep(13);
        if (total % 16 == 0) total += GeneratedStep(14);
        if (total % 17 == 0) total += GeneratedStep(15);
        if (total % 18 == 0) total += GeneratedStep(16);
        if (total % 19 == 0) total += GeneratedStep(17);
        if (total % 20 == 0) total += GeneratedStep(18);
        if (total % 21 == 0) total += GeneratedStep(19);
        if (total % 22 == 0) total += GeneratedStep(20);
        if (total % 23 == 0) total += GeneratedStep(21);
        if (total % 24 == 0) total += GeneratedStep(22);
        if (total % 25 == 0) total += GeneratedStep(23);
        if (total % 26 == 0) total += GeneratedStep(24);
        if (total % 27 == 0) total += GeneratedStep(25);
        if (total % 28 == 0) total += GeneratedStep(26);
        if (total % 29 == 0) total += GeneratedStep(27);
        if (total % 30 == 0) total += GeneratedStep(28);
        if (total % 31 == 0) total += GeneratedStep(29);
        if (total % 32 == 0) total += GeneratedStep(30);
        if (total % 33 == 0) total += GeneratedStep(31);
        if (total % 34 == 0) total += GeneratedStep(32);
        if (total % 35 == 0) total += GeneratedStep(33);
        if (total % 36 == 0) total += GeneratedStep(34);
        if (total % 37 == 0) total += GeneratedStep(35);
        if (total % 38 == 0) total += GeneratedStep(36);
        if (total % 39 == 0) total += GeneratedStep(37);
        if (total % 40 == 0) total += GeneratedStep(38);
        if (total % 41 == 0) total += GeneratedStep(39);
        if (total % 42 == 0) total += GeneratedStep(40);
        if (total % 43 == 0) total += GeneratedStep(41);
        if (total % 44 == 0) total += GeneratedStep(42);
        if (total % 45 == 0) total += GeneratedStep(43);
        if (total % 46 == 0) total += GeneratedStep(44);
        if (total % 47 == 0) total += GeneratedStep(45);
        if (total % 48 == 0) total += GeneratedStep(46);
        if (total % 49 == 0) total += GeneratedStep(47);
        if (total % 50 == 0) total += GeneratedStep(48);
        if (total % 51 == 0) total += GeneratedStep(49);
        if (total % 52 == 0) total += GeneratedStep(50);
        if (total % 53 == 0) total += GeneratedStep(51);
        return total;
    }
}
